### ISSUE TITLE
[logging] clean up code

### ISSUE THREAD

**Issue by gaya-** [cram2/cram#36]

**Comment by gaya-** [comment]
Solved in f1a8a8fcc40ffcc1cd1ac15681704e51247a8bf7. Waiting for @seba90 to review and test changes.

**Comment by seba90** [comment]
I wanted to test the code but I assume we have a circular dependency problem. The utils-for-perform uses due to the keyword "exe:" the cram-executive package. When I want to run the cram-cloud-logger with the pick and place demo I get an error that "exe" cannot be found in utils-for-perform. I added the cram executive package to the asd file of the cloud logger, I get a circular dependency problem.

**Comment by gaya-** [comment]
Oh, the exe is independent of ccl now. I'll get rid of that dependency, just a mom.

**Comment by gaya-** [comment]
Done in 648c5b2d6c6d422fe14a0be1c9ce3b16c5955469

**Comment by gaya-** [comment]
@seba90

**Comment by seba90** [comment]
it works :)
